# Ex No 1.c: Universal Functions
Aim:
To explore the use of universal functions in NumPy for element-wise operations, including mathematical, statistical, and trigonometric functions.
Scenario:
You are working as a data scientist for a sports analytics company. You need to analyze the performance metrics of athletes in a decathlon event. The data includes various performance metrics such as running speeds, jump heights, and throw distances. You need to apply various universal functions to analyze and normalize this data.
Sample Dataset:
performance_data = {
    'running_speed': [10.5, 9.8, 11.2, 10.0, 9.7],
    'jump_height': [2.1, 2.3, 2.0, 2.4, 2.2],
    'throw_distance': [60.5, 62.0, 59.8, 61.2, 63.5]
}
Task to be Performed:
1.	Create a NumPy array for each performance metric.
2.	Calculate the square of the running speeds using a universal function.
3.	Normalize the jump heights by subtracting the mean and dividing by the standard deviation.
4.	Apply the exponential function to the throw distances to model their growth.
5.	Calculate the logarithm of the normalized jump heights to explore the data distribution.
6.	Apply the sine function to the running speeds to study their periodic behavior.


In [ ]:
#1.
import numpy as np
running_speed = np.array([10.5, 9.8, 11.2, 10.0, 9.7])
print("RUNNING SPEED : ",running_speed)
jump_height = np.array([2.1, 2.3, 2.0, 2.4, 2.2])
print("JUMP HEIGHT : ",jump_height)
throw_distance =np.array([60.5, 62.0, 59.8, 61.2, 63.5])
print("THROW DISTANCE : ",throw_distance)
#2.
print("Square of running speeds : ",np.power(2,running_speed))
#3.
mean = np.mean(jump_height)
std = np.std(jump_height)
sub = np.subtract(jump_height,mean)
nor = np.divide(jump_height,sub)
print("Normalized Values : ",nor)
#4.
print("Exponential function : ",np.exp(throw_distance))
#5.
print("Logarithm of the normalized jump heights : ",np.log(nor))
#6.
print("Sine Function : ",np.sin(running_speed))

RUNNING SPEED :  [10.5  9.8 11.2 10.   9.7]
JUMP HEIGHT :  [2.1 2.3 2.  2.4 2.2]
THROW DISTANCE :  [60.5 62.  59.8 61.2 63.5]
Square of running speeds :  [1448.15468787  891.44377682 2352.53423103 1024.          831.74645387]
Normalized Values :  [-21.  23. -10.  12.  inf]
Exponential function :  [1.88285187e+26 8.43835667e+26 9.34996570e+25 3.79159806e+26
 3.78180909e+27]
Logarithm of the normalized jump heights :  [       nan 3.13549422        nan 2.48490665        inf]
Sine Function :  [-0.87969576 -0.36647913 -0.97917773 -0.54402111 -0.27176063]


<ipython-input-18-7f53a1007ec9>:15: RuntimeWarning: divide by zero encountered in true_divide
  nor = np.divide(jump_height,sub)
<ipython-input-18-7f53a1007ec9>:20: RuntimeWarning: invalid value encountered in log
  print("Logarithm of the normalized jump heights : ",np.log(nor))


# Ex No 1.d: Aggregate Functions

Aim:
To use aggregate functions in NumPy for summarizing and analyzing data.

Scenario:
You are a financial analyst examining the monthly returns of different investment portfolios. You need to calculate various aggregate statistics to understand the performance and risk associated with each portfolio.

Sample Dataset:
returns_data = {
    'portfolio_A': [0.05, 0.02, 0.04, 0.03, 0.06, 0.01],
    'portfolio_B': [0.04, 0.03, 0.05, 0.02, 0.01, 0.04],
    'portfolio_C': [0.03, 0.01, 0.02, 0.03, 0.04, 0.05]
}

Task to be Performed:
1.	Create a NumPy array for each portfolio's returns.
2.	Calculate the total return for each portfolio over the six months.
3.	Calculate the mean monthly return for each portfolio.
4.	Find the portfolio with the highest mean return.
5.	Calculate the overall average return across all portfolios.
6.	Determine the variance and standard deviation of the returns for each portfolio to assess risk.


In [ ]:
#1.
import numpy as np
portfolio_A = np.array([0.05, 0.02, 0.04, 0.03, 0.06, 0.01])
portfolio_B = np.array([0.04, 0.03, 0.05, 0.02, 0.01, 0.04])
portfolio_C = np.array([0.03, 0.01, 0.02, 0.03, 0.04, 0.05])
print(portfolio_A)
print(portfolio_B)
print(portfolio_C)
#2.
print("Total Return of A:",np.sum(portfolio_A))
print("Total Return of B:",np.sum(portfolio_B))
print("Total Return of C:",np.sum(portfolio_C))
#3.
print("Mean Return of A:",np.mean(portfolio_A))
print("Mean Return of B:",np.mean(portfolio_B))
print("Mean Return of C:",np.mean(portfolio_C))
#4.
print("Highest Mean Return:",np.mean(portfolio_C))
#5.
avg = portfolio_A + portfolio_B + portfolio_C/3
print("Average return of all portfolios: ",avg)
#6.
print("Variance Return of A:",np.var(portfolio_A))
print("Variance Return of B:",np.var(portfolio_B))
print("variance Return of C:",np.var(portfolio_C))
print("Standard Deviation Return of A:",np.std(portfolio_A))
print("Standard Deviation Return of B:",np.std(portfolio_B))
print("Standard Deviation Return of C:",np.std(portfolio_C))


[0.05 0.02 0.04 0.03 0.06 0.01]
[0.04 0.03 0.05 0.02 0.01 0.04]
[0.03 0.01 0.02 0.03 0.04 0.05]
Total Return of A: 0.21000000000000002
Total Return of B: 0.19000000000000003
Total Return of C: 0.18
Mean Return of A: 0.035
Mean Return of B: 0.03166666666666667
Mean Return of C: 0.03
Highest Mean Return: 0.03
Average return of all portfolios:  [0.1        0.05333333 0.09666667 0.06       0.08333333 0.06666667]
Variance Return of A: 0.00029166666666666664
Variance Return of B: 0.00018055555555555557
variance Return of C: 0.00016666666666666666
Standard Deviation Return of A: 0.01707825127659933
Standard Deviation Return of B: 0.01343709624716425
Standard Deviation Return of C: 0.012909944487358056
